#!/bin/sh

if [ -z "$2" ]
then
	echo
	echo "Script to download the NEWT UniProt taxonomy database and load it"
	echo "to a local MySQL db"
	echo 
	echo "Usage: $0 <output dir to store taxonomy file> <db name>"
	echo "The taxonomy file (NEWT database) will be downloaded from UniProt server"
	echo "and then loaded into local db "
	echo 
	echo "  e.g. $0 /nfs/data/dbs/taxonomy/ uniprot_2013_02"
	echo
	exit 1
fi

taxonfile=$1/taxonomy-all.tab
db=$2


curl "http://www.uniprot.org/taxonomy/?query=*&compress=yes&format=tab" | gunzip > $taxonfile || exit 1


table=taxonomy

# creating tables
echo "Creating table..."
mysql $db <<EOF
DROP TABLE IF EXISTS $table;

CREATE TABLE $table (
 tax_id int PRIMARY KEY,
 mnemonic varchar(20),
 scientific varchar(255),
 common varchar(255),
 synonym varchar(255),
 other text,
 reviewed varchar(20),
 rank varchar(20),
 lineage text,
 parent int
 
);
EOF


# loading data
echo "Loading data..."
mysql --enable-local $db <<EOF
LOAD DATA LOCAL INFILE '$taxonfile' INTO TABLE $table IGNORE 1 LINES;
SHOW WARNINGS;
EOF
