#!/bin/sh

# Define PATHS for directory form where the files are copied
SOURCE_SERVER=biyani_n@merlinl01.psi.ch
SOURCE_DIR=/gpfs/home/duarte_j/eppic-precomp/output/data

# Define destination directory on this server here
DESTINATION_DIR=/data/webapps/files1/

DATE=`date +%F`
CUR_DIR=`pwd`
LOGFILE=$CUR_DIR/sync_${DATE}.log

#rsync divided folder
rsync -r -v -l -z --rsh=ssh $SOURCE_SERVER:$SOURCE_DIR/divided $DESTINATION_DIR > $LOGFILE

#Create symbolic links in DEST_DIR
cd $DESTINATION_DIR/divided
for mid in `ls -1`
do
        cd $mid
        for pdb in `ls -1`
        do
                ln -s -t $DESTINATION_DIR divided/$mid/$pdb
        done
done
