#!/bin/sh

ewuiroot=/data/webapps/ewui
libsdir=$ewuiroot/WEB-INF/lib
export CLASSPATH=\
$ewuiroot/WEB-INF/classes:\
$libsdir/crk.jar:\
$libsdir/hibernate3.jar:\
$libsdir/hibernate-jpa-2.0-api-1.0.0.Final.jar:\
$libsdir/hibernate-jpamodelgen-1.1.1.Final.jar:\
$libsdir/dom4j-1.6.1.jar:\
$libsdir/slf4j-api-1.6.1.jar:\
$libsdir/slf4j-log4j12-1.6.1.jar:\
$libsdir/javassist-3.12.0.GA.jar:\
$libsdir/c3p0-0.9.1.jar:\
$libsdir/commons-collections-3.1.jar:\
$libsdir/commons-fileupload-1.2.2.jar:\
$libsdir/commons-io-2.0.1.jar:\
$libsdir/commons-lang-2.6.jar:\
$libsdir/antlr-2.7.6.jar:\
$libsdir/jta-1.1.jar

java ch.systemsx.sybit.crkwebui.server.db.util.UploadToDb $@
