#!/bin/sh

# --------------------------------------------------------------
#
# Author: Jose Duarte, Nikhil Biyani
# Date: 25/02/2013
#
#---------------------------------------------------------------
help=" Usage: $0 \n
        \t\t     [-o <dir>  : Output Directory(with around 30GB space) \n
        \t\t      -d <string>  : Name of the Database to be created \n
        \t\t      -p <path> : Eppic jar path ]\n
Example:./make-new-uniprot-in-DB -o /home/biyani_n/temp-output -d uniprot_2013_02 -p /gpfs/home/duarte_j/software/jars/eppic.jar\n\n  "

while getopts :o:d:p:h option
do
        case "${option}"
        in
                o) out=${OPTARG};;
                d) db=${OPTARG};;
                p) jar=${OPTARG};;
                h) echo -e $help;;
               \?) print >&2 $help
                   exit 1;;
                :) echo "Option -$OPTARG requires an argument." >&2
                   exit 1;;
        esac
done

if [ -z $out ] || [ -z $db ] || [ -z $jar ]
then
        echo -e "\n ---- SOME OPTIONS NOT SPECIFIED CORRECTLY ---- "
        echo -e $help
        exit 1
fi


###################################################
# Download XML file from switzerland mirror
#-----------------------------------------------
URL=ftp://ftp.expasy.org/databases/uniprot/current_release/uniref/uniref100/uniref100.xml.gz

echo "Downloading xml file from $URL .."
curl $URL > $out/uniref100.xml.gz

if [ $? -ne 0 ]
then
	echo " Downloading failed.. "
	exit 1
fi
#------------------------------------------------



###################################################
# Create output tab and cluster members tab file ..
#--------------------------------------------------------------------------
in=$out/uniref100.xml.gz
outtab=$out/uniref100.tab
outclust=$out/uniref100.clustermembers.tab

echo "Creating output tab and cluster members tab file .. "
cmd="java -cp $jar owl.core.connections.UnirefXMLParser"

$cmd $in $outtab $outclust || exit 1
#---------------------------------------------------------------------------

###############################################
# Building new database...
#-------------------------------------------------------------------------
echo "Creating a new database named $db .."
mysql <<EOF
DROP DATABASE IF EXISTS $db;
CREATE DATABASE $db;
EOF

#------------------------------------------------------------------------



################################################
# Create new tables
#----------------------------------------------------------------
table=uniprot

# note 1: uniprot ids are 6 char, but for isoforms they can be 8 or 9 chars (hyphen and number additionally)

echo "Creating tables.."
mysql $db <<EOF
DROP TABLE IF EXISTS $table;
DROP TABLE IF EXISTS ${table}_clusters;
CREATE TABLE $table (
 id varchar(23),
 uniprot_id varchar(9),
 uniparc_id char(13) PRIMARY KEY,
 tax_id int,
 sequence text
);
CREATE TABLE ${table}_clusters (
 representative varchar(9),
 member varchar(9) PRIMARY KEY,
 tax_id int
);

EOF


#################################################
# Load Data
#--------------------------------------------------------

# NOTE in first versions of uniprot there are duplicate uniprot ids, e.g. Q9WHW0 in version 1.0
echo "Loading Data... "
mysql $db <<EOF
LOAD DATA LOCAL INFILE '$outtab' INTO TABLE $table;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '$outclust' INTO TABLE ${table}_clusters;
SHOW WARNINGS;
EOF

##################################################
# Creating Uniprot Database Indices
#--------------------------------------------------------------
echo "Creating indices.."
mysql $db <<EOF
-- ALTER TABLE uniprot ADD PRIMARY KEY (id);
-- ALTER TABLE uniprot_clusters ADD PRIMARY KEY (member);
CREATE INDEX UNIPROTID_IDX ON uniprot (uniprot_id);
-- CREATE INDEX UNIPARCID_IDX ON uniprot (uniparc_id);
EOF


