#!/bin/sh

#############################################################
#     EXECUTE STEP (B) OF PRECOMPUTE-PIPELINE OF EPPIC      #
#############################################################

# SET Inputs Here (CHECK Before Executing)
UNIPROT_DIR=/gpfs/home/duarte_j/data/uniprot/uniprot_2013_02    # CHECK !!
SCRATCH_DIR=/scratch/biyanin/					# CHECK !!
DB_NAME=uniprot_2013_02						# CHECK !!
BLAST_CACHE_DIR=/gpfs/home/duarte_j/data/blast_cache/           # CHECK !!
CURRENT_DIR=`pwd`

# EXECUTABLE PATHS
BLASTP=/gpfs/home/duarte_j/software/packages/ncbi-blast-2.2.27+/bin/blastp

#--------------------------------------------------
# B1) Copy Files to all nodes
echo "Copying uniprot to all nodes.."
if [! -d $CURRENT_DIR/logs-copy-uniprot/ ]; then mkdir $CURRENT_DIR/logs-copy-uniprot/; fi
./scripts/cp2cluster -s $UNIPROT_DIR -d $SCRATCH_DIR -n $CURRENT_DIR/resources/hosts_sets.lst -l $CURRENT_DIR/logs-copy-uniprot/ || exit 1
#---------------------------------------------------

#--------------------------------------------------
# B2) Create unique fasta files
echo "Creting unique fasta files.."
if [! -d $CURRENT_DIR/unique-uniprot/ ]; then mkdir $CURRENT_DIR/unique-uniprot/; fi
./scripts/create-unique-fasta -s $UNIPROT_DIR/pdb_chain_uniprot.lst -u $DB_NAME -o $CURRENT_DIR/unique-uniprot/ > $CURRENT_DIR/write-fasta.log || exit 1
#--------------------------------------------------

#--------------------------------------------------
# B3) Create Blast Cache
echo "Creating blast-cache directory $BLAST_CACHE_DIR/$DB_NAME.."
if [! -d $BLAST_CACHE_DIR/$DB_NAME ]; then mkdir $BLAST_CACHE_DIR/$DB_NAME; fi || exit 1
if [! -d $CURRENT_DIR/logs-blast/ ]; then mkdir $CURRENT_DIR/logs-blast/; fi || exit 1
cp $UNIPROT_DIR/reldate.txt $BLAST_CACHE_DIR/$DB_NAME/ || exit 1
echo "Creating blast-cache in $BLAST_CACHE_DIR/$DB_NAME.."
./scripts/blast_the_pdb -i $CURRENT_DIR/unique-uniprot/ -o $BLAST_CACHE_DIR/$DB_NAME/ -l $CURRENT_DIR/logs-blast/ -f $CURRENT_DIR/unique-uniprot/queries.list -d $SCRATCH_DIR/$DB_NAME/ -p $BLASTP || exit 1
#-------------------------------------------------- 

#-------------------------------------------------
# B4) Remove from scratch
# echo "Removing from Scratch.."
#./scripts/rm-from-cluster -d $SCRATCH_DIR/$DB_NAME -n $CURRENT_DIR/resources/hosts_sets.lst
#------------------------------------------------

echo Do not forget to remove the temporary files from scratch !!!
