#!/bin/bash
#**************************************************************
#  EPPIC Pre-Computation Script
#  Author : Kumaran Baskaran
#  Date   : 05/07/2013
#***************************************************************

fgrep -v "non-standard" $1 | grep -v "Clashes" | grep -v "non-protein" | grep -v "no protein" | grep -v "space group" | grep -v "_atom_site" | grep -v "no observed residues" | grep -v "Inconsistent PDB entry" | grep -v "Can't continue" | grep -v "Mix of protein and nucleotide sequences" 

