#!/bin/bash

#---------------------------------------------------------------------
# Script will do the following jobs
#       1) Compare the input pdb list with the output and finds the missing
#	2) generate pdb list for unfinished jobs
# Author : Kumaran Baskaran
# Date   : 06/06/2013
#
# 
# Note : This script is based on the dir structure created by Jose and Nikil script.
#
#
#
#----------------------------------------------------------------------------

help="Usage: $0 \n
	\t [ -l file : file contains pdblist \n
	\t   -o dir  : output dir of the merlin jobs \n]"

rerun=final_01 # edit this according to the number of reruns



while getopts :l:o:h option
do
        case "${option}"
        in
		l) inputlist=${OPTARG};;
		o) outfolder=${OPTARG};;
                h) echo -e $help;;
               \?) print >&2 $help
                   exit 1;;
                :) echo "Option -$OPTARG requires an argument." >&2
                   exit 1;;
        esac
done

if [[ -z $inputlist ]] || [[ -z $outfolder ]] 
then
	echo -e "\n ----SOME OPTIONS NOT SPECIFIED CORRECTLY------"
	echo -e $help
	exit 1
fi
oldlist=`basename $inputlist`   # file name extraction to replace in the qsub script
newlist=${inputlist%.*}_$rerun.list # new filename for the missing pdb list
newlistbase=`basename $newlist` # file name extraction to replace in the qsub script
newblacklist=${inputlist%.*}_$rerun.blist

if [[ -e $newlist ]]
then
	rm $newlist
fi

if [[ -e $newblacklist ]]
then
	rm $newblacklist
fi
# compare input list to output log and write output in a new pdb list file
for i in $(cat $inputlist)
do
	if [[ -e $outfolder/all/$i/$i.log ]] 
	then
		isfinished=`fgrep Finished $outfolder/all/$i/$i.log`
		if [[ -z $isfinished ]]
		then
			ismemoryerror=`fgrep "Cannot allocate memory" $outfolder/all/$i/$i.log`
			pymolerr=`fgrep "Couldn't write thumbnails" $outfolder/all/$i/$i.log`
			javamem=`tail -1 $outfolder/all/$i/$i.log | grep "Running in host"`
			strange=`tail -1 $outfolder/all/$i/$i.log | grep "INFO"`
			concurrency=`tail -1 $outfolder/all/$i/$i.log | grep "File does not conform with"`
			sqlproblem=`tail -1 $outfolder/all/$i/$i.log | grep "Too many connections"`
			nolog=`cat $outfolder/all/$i/$i.log`
			diskquota=`tail -1 $outfolder/all/$i/$i.log | grep "Disk quota exceeded"`
			diskquota2=`tail -1 $outfolder/all/$i/$i.log | grep "WARN"`
			fastaerr=`tail -1 $outfolder/all/$i/$i.log | grep "FASTA header"`
			xmlerror=`tail -1 $outfolder/all/$i/$i.log | grep "Premature end of file"`
			if [[ -z $ismemoryerror ]] && [[ -z $pymolerr ]] && [[ -z $javamem ]] && [[ -z $strange ]] && [[ -z $concurrency ]] && [[ -z $sqlproblem ]] && [[ ! -z $nolog ]] && [[ -z $diskquota ]] && [[ -z $fastaerr ]] && [[ -z $xmlerror ]] && [[ -z $diskquota2 ]]
			then
				errmsg=`tail -1 $outfolder/all/$i/$i.log`
				echo $i $errmsg >> $newblacklist
			
			else
				echo $i >> $newlist
			fi
		#else
		#	echo $pdb $isfinished
		fi
	else
		echo $i >> $newlist 
	fi 
done 

count=`cat $newlist | wc -l` # counts the missine pdbs
bcount=`cat $newblacklist | wc -l`

echo "$count unfinished jobs found"
echo "$bcount pdbs could not be handled"
# thats all.. submit the new jobs to merlin
