#!/bin/bash

# --------------------------------------------------------------
# Script to remove files from a number of host nodes
#
# Author: Nikhil Biyani
# Date: 25/02/2013
#
# ------------------------------------------------------------

# --------------------------------------------------------------
# Example Usage
#./rm-from-cluster -d /scratch/biyani_n/uniprot_2013_01 -n /blast/merlin-nodes.list
# ----------------------------------------------------------------

help=" Usage: $0 \n
        Script to remove files to all nodes in cluster.\n
        \t\t     [-d <dir>  : Directory ( must be local to the node. Can only be of form /scratch/<YOUR_DIR> )\n
        \t\t      -n <file> : File specifying set of host nodes where the files are to be removed from ]\n
Example: ./rm-from-cluster -d /scratch/biyani_n/uniprot_2013_01 -n /blast/merlin-nodes.list\n"

while getopts :d:n:h option
do
        case "${option}"
        in
                d) destdir=${OPTARG};;
                n) hfile=${OPTARG};;
                h) echo -e $help;;
               \?) print >&2 $help
                   exit 1;;
                :) echo "Option -$OPTARG requires an argument." >&2
                   exit 1;;
        esac
done

if [[ -z $destdir ]] || [[ -z $hfile ]]
then
        echo -e "\n ---- SOME OPTIONS NOT SPECIFIED CORRECTLY ---- "
        echo -e $help
        exit 1
fi

if [ ! -f $hfile ]
then
        echo File $hfile can\'t be read
	exit 1
fi

allnodes=`cat $hfile`

cmd="rm -rf $destdir"
count=1

for node in $allnodes
do
        echo $node...; ssh $node $cmd
done

